//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiRelacionados
    {
        public int orden { get; set; }
        public short soptypeFrom { get; set; }
        public string sopnumbeFrom { get; set; }
        public int soptypeTo { get; set; }
        public string sopnumbeTo { get; set; }
        public Nullable<int> codigoInterno { get; set; }
        public int discrepancyResponse { get; set; }
        public int billingReference { get; set; }
        public string cufeDocReferenciado { get; set; }
        public string codigoEstatusDocumento { get; set; }
        public string cufeDescripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string numeroDocumento { get; set; }
        public Nullable<int> tipoDocumento { get; set; }
        public string tipoCufe { get; set; }
    }
}
