//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiGeneraDocumentoDeVenta
    {
        public short soptype { get; set; }
        public string sopnumbe { get; set; }
        public string custnmbr { get; set; }
        public Nullable<int> cantidadDecimales { get; set; }
        public string consecutivoDocumento { get; set; }
        public string cargosdescuentos_codigo { get; set; }
        public string cargosdescuentos_descripcion { get; set; }
        public string cargosdescuentos_indicador { get; set; }
        public decimal cargosdescuentos_monto { get; set; }
        public decimal cargosdescuentos_montobase { get; set; }
        public Nullable<decimal> cargodescuentos_porcentaje { get; set; }
        public string cargosdescuentos_secuencia { get; set; }
        public string cliente_nitProveedorReceptor { get; set; }
        public string cliente_telefono { get; set; }
        public string cliente_difCiudad { get; set; }
        public string cliente_difcodigoDepartamento { get; set; }
        public string cliente_difdepartamento { get; set; }
        public string cliente_difdireccion { get; set; }
        public string cliente_diflenguaje { get; set; }
        public string cliente_difmunicipio { get; set; }
        public string cliente_difpais { get; set; }
        public string cliente_difzonapostal { get; set; }
        public string cliente_email { get; set; }
        public string cliente_nombreRegistroRUT { get; set; }
        public string cliente_numeroIdentificacion { get; set; }
        public string cliente_numeroIdentificacionDV { get; set; }
        public string cliente_tipoIdentificacion { get; set; }
        public string cliente_nombreComercial { get; set; }
        public string cliente_nombreRazonSocial { get; set; }
        public string cliente_notificar { get; set; }
        public string cliente_numeroDocumento { get; set; }
        public string cliente_tipoPersona { get; set; }
        public string cliente_actividadEconomicaCIIU { get; set; }
        public string fechaEmision { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public string moneda { get; set; }
        public string rangonumeracion { get; set; }
        public int redondeoaplicado { get; set; }
        public decimal tasaDeCambio { get; set; }
        public string tipoDocumento { get; set; }
        public string tipoOperacion { get; set; }
        public Nullable<decimal> totalBaseImponible { get; set; }
        public Nullable<decimal> totalSinImpuestos { get; set; }
        public decimal totalBrutoconImpuestos { get; set; }
        public decimal totalMonto { get; set; }
        public int totalProductos { get; set; }
        public string prefijo { get; set; }
    }
}
