//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiFacturaImpuestosCabecera
    {
        public short soptype { get; set; }
        public string sopnumbe { get; set; }
        public string codigoTotalImp { get; set; }
        public decimal porcentajeTotalImp { get; set; }
        public Nullable<decimal> staxamnt { get; set; }
        public Nullable<decimal> valorTotalImp { get; set; }
        public Nullable<decimal> tdttxsls { get; set; }
        public Nullable<decimal> baseImponibleTotalImp { get; set; }
        public Nullable<int> controlInterno { get; set; }
        public string unidadMedida { get; set; }
        public Nullable<int> unidadMedidaTributo { get; set; }
        public Nullable<int> valorTributoUnidad { get; set; }
    }
}
