//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiFacturaImpuestosDetalles
    {
        public short soptype { get; set; }
        public string sopnumbe { get; set; }
        public int LNITMSEQ { get; set; }
        public string itemnmbr { get; set; }
        public int cmpntseq { get; set; }
        public string codigoTotalImp { get; set; }
        public decimal porcentajeTotalImp { get; set; }
        public Nullable<decimal> staxamnt { get; set; }
        public Nullable<decimal> valorTotalImp { get; set; }
        public Nullable<decimal> tdttxsls { get; set; }
        public Nullable<decimal> baseImponibleTotalImp { get; set; }
        public string controlInterno { get; set; }
        public string unidadMedida { get; set; }
        public string unidadMedidaTributo { get; set; }
        public string valorTributoUnidad { get; set; }
    }
}
