//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiConceptos
    {
        public Nullable<long> facturadetalle_secuencia { get; set; }
        public short soptype { get; set; }
        public string sopnumbe { get; set; }
        public int LNITMSEQ { get; set; }
        public string ITEMNMBR { get; set; }
        public string SERLTNUM { get; set; }
        public int CMPNTSEQ { get; set; }
        public decimal facturadetalle_cantidadreal { get; set; }
        public string facturadetalle_cantidadrealunidadmedida { get; set; }
        public decimal facturadetalle_cantidadunidades { get; set; }
        public Nullable<int> facturadetalle_cantidadporempaque { get; set; }
        public Nullable<int> cargosdescuentos_codigo { get; set; }
        public string cargosdescuentos_descripcion { get; set; }
        public int cargosdescuentos_indicador { get; set; }
        public int cargosdescuentos_monto { get; set; }
        public int cargosdescuentos_montobase { get; set; }
        public int cargodescuentos_porcentaje { get; set; }
        public string cargosdescuentos_secuencia { get; set; }
        public string facturadetalle_codigoproducto { get; set; }
        public string facturadetalle_descripcion { get; set; }
        public string facturadetalle_estandarcodigo { get; set; }
        public string facturadetalle_estandarcodigoproducto { get; set; }
        public string facturadetalle_marca { get; set; }
        public string facturadetalle_modelo { get; set; }
        public Nullable<decimal> facturadetalle_precioTotal { get; set; }
        public decimal facturadetalle_precioTotalSinImpuestos { get; set; }
        public decimal facturadetalle_precioVentaUnitario { get; set; }
        public string facturadetalle_unidadMedida { get; set; }
    }
}
