//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiMediosDePago
    {
        public short APTODCTY { get; set; }
        public Nullable<int> soptype { get; set; }
        public string sopnumbe { get; set; }
        public short APFRDCTY { get; set; }
        public string APFRDCNM { get; set; }
        public string mediopago { get; set; }
        public string metodopago { get; set; }
        public string numeroreferencia { get; set; }
    }
}
