//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="uploadAttachment", Namespace="http://schemas.datacontract.org/2004/07/Services.wsEmision.Request")]
    [System.SerializableAttribute()]
    public partial class uploadAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] archivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enviarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                if ((object.ReferenceEquals(this.archivoField, value) != true)) {
                    this.archivoField = value;
                    this.RaisePropertyChanged("archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enviar {
            get {
                return this.enviarField;
            }
            set {
                if ((object.ReferenceEquals(this.enviarField, value) != true)) {
                    this.enviarField = value;
                    this.RaisePropertyChanged("enviar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formato {
            get {
                return this.formatoField;
            }
            set {
                if ((object.ReferenceEquals(this.formatoField, value) != true)) {
                    this.formatoField = value;
                    this.RaisePropertyChanged("formato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroDocumentoField, value) != true)) {
                    this.numeroDocumentoField = value;
                    this.RaisePropertyChanged("numeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tokenEmpresa {
            get {
                return this.tokenEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenEmpresaField, value) != true)) {
                    this.tokenEmpresaField = value;
                    this.RaisePropertyChanged("tokenEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tokenPassword {
            get {
                return this.tokenPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenPasswordField, value) != true)) {
                    this.tokenPasswordField = value;
                    this.RaisePropertyChanged("tokenPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileUploadResponse", Namespace="http://schemas.datacontract.org/2004/07/Services.ResponseFile")]
    [System.SerializableAttribute()]
    public partial class FileUploadResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDemoEnviarArchivo.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EnviarArchivo", ReplyAction="http://tempuri.org/IService/EnviarArchivoResponse")]
        DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.FileUploadResponse EnviarArchivo(DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.uploadAttachment data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EnviarArchivo", ReplyAction="http://tempuri.org/IService/EnviarArchivoResponse")]
        System.Threading.Tasks.Task<DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.FileUploadResponse> EnviarArchivoAsync(DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.uploadAttachment data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.IService>, DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.FileUploadResponse EnviarArchivo(DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.uploadAttachment data) {
            return base.Channel.EnviarArchivo(data);
        }
        
        public System.Threading.Tasks.Task<DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.FileUploadResponse> EnviarArchivoAsync(DemoGenFactura_int_tfhka_fel.ServiceDemoEnviarArchivo.uploadAttachment data) {
            return base.Channel.EnviarArchivoAsync(data);
        }
    }
}
